### PR TITLE
[1.14.4] Immersive Petroleum CrT Docs

### PR DESCRIPTION
**Pull request by TwistedGate**
Contains the Updated version of all changed Immersive Petroleum CrT methods.

### CODE REVIEW

**Comment by kindlich** [comment]
Showing the builder methods using the `mods....` prefix gives the impression that they are static methods instead of instance methods. That may be confusing for the readers.

**Comment by TwistedGate** [comment]
How would i convey them to be a non-static methods?

**Comment by kindlich** [comment]
> How would i convey them to be a non-static methods?
Usually we use a "direct" call style, so something like `myBuilder.setOutputFluids([<fluid:minecraft:water> * 10])`

**Comment by TwistedGate** [comment]
How about this?

**Pull request merged**
