### PR TITLE
[1.14] StoneAge mod doc

### PR DESCRIPTION
**Pull request by yanny7**
Documentation for CrT compatibility

### CODE REVIEW

**Comment by jaredlll08** [comment]
Is your mod for both 1.14 and 1.15? If not, could you please specify which one it is for in the markdown files :)

**Comment by yanny7** [comment]
It is for both 1.14 and 1.15

**Comment by yanny7** [comment]
I am supporting both versions, so there is not difference

**Comment by yanny7** [comment]
Can be merged now

**Pull request merged**
