### PR TITLE
[1.19.4] Documentation for The Aether mod.

### PR DESCRIPTION
**Pull request by bconlon1**
Adds documentation for The Aether's CraftTweaker compatibility. This includes methods for manipulating the fuel items for the Altar, Freezer, and Incubator.

### CODE REVIEW

**Comment by bconlon1** [comment]
Updated documentation according to changing methods to be static.

**Comment by Witixin1512** [comment]
Is there any reason for requiring an MCTag or an IItemStack as arguments instead of just IIngredient?

**Comment by Witixin1512** [comment]
Why does removing an item require a user to know the previous burn time? How are they supposed to check it?

**Comment by bconlon1** [comment]
Updated documentation after changing methods to use IIngredient and removeFuel no longer needing a burn time parameter.

**Review by Witixin1512 — APPROVED** [review]

**Comment by jaredlll08** [comment]
@bconlon1 could you please reply here when the update is released so we can go ahead and merge this, thanks!

**Comment by bconlon1** [comment]
The update with this compat has now been released, you are free to merge the PR.

**Pull request merged**
