### PR TITLE
Added instruction for custom commands

### PR DESCRIPTION
**Pull request by Riernar**
Since adding "custom" commands for modpacks is possible yet quite tricky, I documented my solution

### CODE REVIEW

**Comment by Riernar** [comment]
Added link to Artisan Worktable documentation to close #212

**Comment by Riernar** [comment]
According to the Travis log, the build error is not due to the change I did ? Do you understand what went wrong @kindlich @jaredlll08 ?

**Comment by kindlich** [comment]
Seems they changed some things in LinkChecker, I'll probably need to set it to a fixed version number later

**Comment by Riernar** [comment]
@kindlich ok! If changes are necessary in the PR, let me know :)

**Comment by kindlich** [comment]
Hm... the build is fixed.

I'm not sure if this should be put in the wiki, though.
While it works, it (ab)uses an event mechanism that was not meant to be used like that...

@jaredlll08 what do you think?

**Comment by Riernar** [comment]
@kindlich Where would that fit ? Maybe in crattweaker-examples ?

Concerning the event, how was it supposed to be used ? The example given on craftweaker-example only allows to react to existing commands, which is not very useful for packs in my opinion. However, packs commands can be very useful.

**Comment by kindlich** [comment]
The command event handler was simply added since it is an event handler that exists in MC and was easily convertable to CrT.

It could be used for various things, like only granting players to use a `/home` command if they have hold a special item in their hand, for example.


Feel free to create a PR explaining featuring your script in the examples repo and I'll add it there, but as I already stated, it's an application of an event that was not made to be used like that so I don't want it on the wiki.

**Comment by jaredlll08** [comment]
Closing because this will never be on the docs page. maybe in an example repo, but not in the docs.

**Pull request closed without merging**
