### PR TITLE
Add SDM CraftTweaker Plus Docs

### PR DESCRIPTION
**Pull request by SagaDeoMissTeam**

### CODE REVIEW

**Comment by jaredlll08** [comment]
Could I get a link to the mod you are adding support for please, I'm not finding anything on github or curseforge for it.

**Comment by SagaDeoMissTeam** [comment]
https://github.com/SagaDeoMissTeam/SDNCraftTwkeaerPlus

**Comment by SagaDeoMissTeam** [comment]
> Could I get a link to the mod you are adding support for please, I'm not finding anything on github or curseforge for it.

https://github.com/SagaDeoMissTeam/SDNCraftTwkeaerPlus

**Comment by jaredlll08** [comment]
While I appreciate the work you've put into this I do not feel comfortable hosting the documentation for your project on the official site. Some of the classes and methods you expose pose a risk to users. For example we intentionally do not expose file IO because it would allow malicious servers and modpack scripts to target users, alter files, and leak sensitive information. We also prefer that the vanilla codebase like `BlockGetter` is exposed through the CraftTweaker mod to avoid confusion and conflicts with addons in future updates.

**Comment by SagaDeoMissTeam** [comment]
> While I appreciate the work you've put into this I do not feel comfortable hosting the documentation for your project on the official site. Some of the classes and methods you expose pose a risk to users. For example we intentionally do not expose file IO because it would allow malicious servers and modpack scripts to target users, alter files, and leak sensitive information. We also prefer that the vanilla codebase like `BlockGetter` is exposed through the CraftTweaker mod to avoid confusion and conflicts with addons in future updates.

As I understand it , should I remove the file system support ?

**Pull request closed without merging**
